### ISSUE TITLE
Add simple env vars replacement in configs

### ISSUE THREAD

**Issue by queil** [queil/rooz#42]
Like:

```yaml

vars:
  SOME_URL: https://rooz.dev

env:
  BETTER_URL: ${{ SOME_URL }}/api/v5
```
